spring:
    application:
        name: PW_BE

    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/myappdb}
        username: ${SPRING_DATASOURCE_USERNAME:admin}
        password: ${SPRING_DATASOURCE_PASSWORD:admin123}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true

    sql:
        init:
            mode: always

#    liquibase:
#        enabled: true
#        change-log: classpath:db/changelog/changelog-master.yaml

server:
    port: 8080

logging:
    level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Configurazione AI Service
ai:
    service:
        url: ${AI_SERVICE_URL:http://localhost:5001}
